// Copyright (c) 2015, 2026, Oracle and/or its affiliates.

//-----------------------------------------------------------------------------
//
// This software is dual-licensed to you under the Universal Permissive License
// (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl and Apache License
// 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose
// either license.
//
// If you elect to accept the software under the Apache License, Version 2.0,
// the following applies:
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-----------------------------------------------------------------------------



// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

const config = standard.jestConfig();

config.setupFilesAfterEnv = ['<rootDir>/src/setupTests.ts'];

config.moduleNameMapper = {
  ...(config.moduleNameMapper || {}),
  '^@grafana/runtime/src$': '@grafana/runtime',
};

config.cache = true;
config.maxWorkers = '50%';
config.testPathIgnorePatterns = ['/node_modules/', '/dist/'];

config.coveragePathIgnorePatterns= [
  "/node_modules/",
  "src/styles.ts",
  "src/module.ts",
  "src/types.ts",
  "src/img/",
  "src/test/",
];
module.exports = config;


